### ISSUE TITLE
Error with Psr\Log\LoggerInterface declaration

### ISSUE THREAD

**Issue by antonpequeno** [laravel-json-api/neomerx-json-api#4]
Hi, 

When I try to run my installation I get this error:

`Declaration of Neomerx\JsonApi\Factories\Factory::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void`

I am using this library via: "cloudcreativity/laravel-json-api": "4.*"

Thanks in advance, Regards!

**Comment by lindyhopchris** [comment]
Thanks for reporting, sorry this has taken a while to get to.

I'm not sure how you've ended up with this error, as you should be locked to PSR Log v1, but seems you've somehow got either v2 or v3 of it. However, this package should support all three of those versions - so I've broadened the requirement in the `composer.json` and fixed the type-hinting. This should solve the problem for you.

Have tagged `laravel-json-api/neomerx-json-api` at `v1.2.0` that solves the problem.

About to tag `v4.1.0` of this package.
