### ISSUE TITLE
Property used before initialisation

### ISSUE THREAD

**Issue by fisharebest** [laravel-json-api/neomerx-json-api#5]
I'm upgrading my application to version 6.0.0 of `cloud-creativity/laravel-json-api`, which includes this package.

I'm getting an error in [src/Schema/Error.php](https://github.com/laravel-json-api/neomerx-json-api/blob/master/src/Schema/Error.php).  It happens in the laravel exception handler when I'm handling an authentication error - i.e. not a json-api error.

This class has a property `$links`, which is defined as:

https://github.com/laravel-json-api/neomerx-json-api/blob/c687b127eb4afbf10ce60976a4beba75d05d78ce/src/Schema/Error.php#L40

The constructor initialises it by calling `setLink()`:

https://github.com/laravel-json-api/neomerx-json-api/blob/c687b127eb4afbf10ce60976a4beba75d05d78ce/src/Schema/Error.php#L171-L180

It is then accessed using getLinks():

https://github.com/laravel-json-api/neomerx-json-api/blob/c687b127eb4afbf10ce60976a4beba75d05d78ce/src/Schema/Error.php#L150-L153

The problem is that when the `$link` parameter to `setLink()` is null, then the call to `unset()` doesn't actually initialise the property, and the following error is generated when you call `getLink()`:

`Uncaught Error: Typed property Neomerx\\JsonApi\\Schema\\Error::$links must not be accessed before initialization in /Users/gr4376/Projects/nquire/vendor/laravel-json-api/neomerx-json-api/src/Schema/Error.php:152`.

AFAICT, the fix is simply to initialise the property:

`private ?iterable $links = null;`

**Comment by lindyhopchris** [comment]
Thanks for reporting. This is definitely a bug. I think I need to take a look at it, both to add tests covering this scenario plus also look at why it's type-hinted as an `iterable`, when it is being treated as an `array`.

**Comment by lindyhopchris** [comment]
This has been fixed in `5.0.2`.
