### ISSUE TITLE
Framework agnostic?

### ISSUE THREAD

**Issue by maclonghorn** [laravel-json-api/neomerx-json-api#7]
The original neomerx package was framework agnostic.  After the fork, this rep also says it's "framework" agnostic in the info panel.  However, the repo title suggests it is Laravel only.  Which is correct?  And if it's Laravel only, why was that change made?

**Comment by lindyhopchris** [comment]
It is still framework agnostic. It's just it's being maintained in the Laravel JSON:API organisation. There's no plans to remove the framework agnostic aspect of it - but it made sense forking it into this organisation as it's a critical package to the overall Laravel JSON:API implementation.

I maybe should update the README to make it clear that this package remains framework agnostic.

**Comment by maclonghorn** [comment]
Ok good to know.  That makes sense.  Thanks.
